// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0o5lsiqvTm83Q7YDK4WTCtotcCoq1zAk',
    appId: '1:479407997771:web:530f7c8711b0ea0e361ece',
    messagingSenderId: '479407997771',
    projectId: 'to-do-list-56e6f',
    authDomain: 'to-do-list-56e6f.firebaseapp.com',
    storageBucket: 'to-do-list-56e6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTqS-1B43lFV5xXc1tIh9vEgQLaZ4B44s',
    appId: '1:479407997771:android:2e6a8bfa7d88f1ba361ece',
    messagingSenderId: '479407997771',
    projectId: 'to-do-list-56e6f',
    storageBucket: 'to-do-list-56e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8XsTfoFB8WYRpsPeOXVJc0wCrUb3hBgI',
    appId: '1:479407997771:ios:6b2a49e1742a5432361ece',
    messagingSenderId: '479407997771',
    projectId: 'to-do-list-56e6f',
    storageBucket: 'to-do-list-56e6f.appspot.com',
    iosClientId: '479407997771-o96bt47kv10570bt2fqgeglpot9a4mts.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8XsTfoFB8WYRpsPeOXVJc0wCrUb3hBgI',
    appId: '1:479407997771:ios:0a6b2912d884dbbf361ece',
    messagingSenderId: '479407997771',
    projectId: 'to-do-list-56e6f',
    storageBucket: 'to-do-list-56e6f.appspot.com',
    iosClientId: '479407997771-l6h773q10b0muq6qmftfkl5gle42p56d.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
